import { describe, expect, test } from "vitest";

import { buildWebhookDeliveryDryRunReport } from "./webhook-delivery-batch";
import type { WebhookEndpointRow } from "./webhook-endpoint-service";

const endpoints: WebhookEndpointRow[] = [
  {
    companyId: "company-1",
    createdAt: "2026-07-12T10:00:00.000Z",
    createdBy: "user-1",
    eventTypes: ["invoice.created"],
    id: "endpoint-1",
    isActive: true,
    name: "Fatura",
    periodId: "period-1",
    secretPrefix: "whsec_one",
    tenantId: "tenant-1",
    updatedAt: "2026-07-12T10:00:00.000Z",
    url: "https://hooks.example.com/fatura",
  },
  {
    companyId: "company-1",
    createdAt: "2026-07-12T11:00:00.000Z",
    createdBy: "user-1",
    eventTypes: ["invoice.status.changed"],
    id: "endpoint-2",
    isActive: true,
    name: "Durum",
    periodId: "period-1",
    secretPrefix: "whsec_two",
    tenantId: "tenant-1",
    updatedAt: "2026-07-12T11:00:00.000Z",
    url: "https://hooks.example.com/durum",
  },
];

describe("webhook delivery batch", () => {
  test("builds a dry-run report without a network call", () => {
    expect(
      buildWebhookDeliveryDryRunReport({
        endpoints,
        eventType: "invoice.created",
        now: () => new Date("2026-07-12T12:00:00.000Z"),
      }),
    ).toEqual({
      attempts: [
        {
          body: JSON.stringify({
            eventType: "invoice.created",
            preparedAt: "2026-07-12T12:00:00.000Z",
          }),
          endpointId: "endpoint-1",
          endpointName: "Fatura",
          endpointUrl: "https://hooks.example.com/fatura",
          eventType: "invoice.created",
          headers: {
            "content-type": "application/json",
            "x-noa-webhook-signature": "[signature will be generated by worker]",
          },
          retryPolicy: {
            backoffSeconds: [30, 120, 600],
            maxAttempts: 3,
            strategyLabel: "Üssel geri deneme",
          },
          signatureHeaderName: "x-noa-webhook-signature",
          transport: "HTTPS/JSON + HMAC-SHA256",
        },
      ],
      body: JSON.stringify({
        eventType: "invoice.created",
        preparedAt: "2026-07-12T12:00:00.000Z",
      }),
      eventType: "invoice.created",
      preparedAt: "2026-07-12T12:00:00.000Z",
      plan: {
        deliverable: true,
        eventType: "invoice.created",
        matchingEndpointCount: 1,
        targets: [
          {
            createdAt: "2026-07-12T10:00:00.000Z",
            endpointId: "endpoint-1",
            endpointName: "Fatura",
            endpointUrl: "https://hooks.example.com/fatura",
            eventTypes: ["invoice.created"],
            secretPrefix: "whsec_one",
          },
        ],
        unroutableReason: null,
      },
      signatureHeaderName: "x-noa-webhook-signature",
      transport: "HTTPS/JSON + HMAC-SHA256",
    });
  });
});
