import type { WebhookDeliveryEventType } from "./webhook-delivery-events";
import { planWebhookDeliveries } from "./webhook-delivery-planner";
import { type WebhookDeliveryRetryPolicy } from "./webhook-delivery-dispatch";
import type { WebhookEndpointRow } from "./webhook-endpoint-service";

export type WebhookDeliveryDryRunAttempt = {
  body: string;
  endpointId: string;
  endpointName: string;
  endpointUrl: string;
  eventType: WebhookDeliveryEventType;
  headers: Record<string, string>;
  retryPolicy: WebhookDeliveryRetryPolicy;
  signatureHeaderName: string;
  transport: "HTTPS/JSON + HMAC-SHA256";
};

export type WebhookDeliveryDryRunReport = {
  attempts: WebhookDeliveryDryRunAttempt[];
  body: string;
  eventType: WebhookDeliveryEventType;
  preparedAt: string;
  plan: ReturnType<typeof planWebhookDeliveries>;
  signatureHeaderName: string;
  transport: "HTTPS/JSON + HMAC-SHA256";
};

export function buildWebhookDeliveryDryRunReport(input: {
  body?: unknown;
  endpoints: WebhookEndpointRow[];
  eventType: WebhookDeliveryEventType;
  now?: () => Date;
}) {
  const preparedAt = (input.now ?? (() => new Date()))().toISOString();
  const body = JSON.stringify(
    input.body ?? {
      eventType: input.eventType,
      preparedAt,
    },
  );
  const plan = planWebhookDeliveries({
    endpoints: input.endpoints,
    eventType: input.eventType,
  });
  const signatureHeaderName = "x-noa-webhook-signature";
  const retryPolicy: WebhookDeliveryRetryPolicy = {
    backoffSeconds: [30, 120, 600],
    maxAttempts: 3,
    strategyLabel: "Üssel geri deneme",
  };

  return {
    attempts: plan.targets.map((target) => ({
      body,
      endpointId: target.endpointId,
      endpointName: target.endpointName,
      endpointUrl: target.endpointUrl,
      eventType: input.eventType,
      headers: {
        "content-type": "application/json",
        [signatureHeaderName]: "[signature will be generated by worker]",
      },
      retryPolicy,
      signatureHeaderName,
      transport: "HTTPS/JSON + HMAC-SHA256",
    })),
    body,
    eventType: input.eventType,
    preparedAt,
    plan,
    signatureHeaderName,
    transport: "HTTPS/JSON + HMAC-SHA256",
  } satisfies WebhookDeliveryDryRunReport;
}
