import { beforeEach, describe, expect, test, vi } from "vitest";

const authenticateBearerApiKeyMock = vi.hoisted(() => vi.fn());
const apiKeyRepositoryMock = vi.hoisted(() => ({ kind: "api-key-repo" }));
const webhookEndpointRepositoryMock = vi.hoisted(() => ({
  list: vi.fn(),
  kind: "webhook-endpoint-repo",
}));

vi.mock("@/lib/prisma", () => ({ prisma: {} }));
vi.mock("@/lib/api-key-prisma-repository", () => ({
  createApiKeyPrismaRepository: vi.fn(() => apiKeyRepositoryMock),
}));
vi.mock("@/lib/webhook-endpoint-prisma-repository", () => ({
  createWebhookEndpointPrismaRepository: vi.fn(() => webhookEndpointRepositoryMock),
}));
vi.mock("@/lib/api-key-auth", () => ({
  authenticateBearerApiKey: authenticateBearerApiKeyMock,
  buildTenantScopeFromApiKey: vi.fn(() => ({
    companyId: "company-1",
    companyName: "API Company",
    licenseLabel: "API",
    periodId: "period-1",
    periodLabel: "API",
    tenantId: "tenant-1",
    tenantName: "API Tenant",
    userId: "user-1",
    userName: "API Kullanıcısı",
    userRole: "viewer",
  })),
}));

import { POST } from "./route";

beforeEach(() => {
  vi.clearAllMocks();
});

describe("webhook delivery dry-run api route", () => {
  test("returns a scoped dry-run report without dispatching an HTTP request", async () => {
    authenticateBearerApiKeyMock.mockResolvedValue({
      ok: true,
      data: {
        apiKey: {
          companyId: "company-1",
          createdBy: "user-1",
          id: "api-key-webhooks",
          periodId: "period-1",
          tenantId: "tenant-1",
        },
      },
    });
    webhookEndpointRepositoryMock.list.mockResolvedValue([
      {
        createdAt: "2026-07-12T10:00:00.000Z",
        eventTypes: ["invoice.created"],
        id: "webhook-endpoint-1",
        isActive: true,
        name: "Fatura Bildirimi",
        secretPrefix: "noa_whsec_123456",
        url: "https://hooks.example.com/webhooks/noa",
      },
      {
        createdAt: "2026-07-12T09:00:00.000Z",
        eventTypes: ["invoice.created"],
        id: "webhook-endpoint-2",
        isActive: false,
        name: "Pasif Bildirim",
        secretPrefix: "noa_whsec_654321",
        url: "https://hooks.example.com/webhooks/pasif",
      },
    ]);

    const response = await POST(
      new Request("http://localhost/api/webhooks/dry-run", {
        body: JSON.stringify({
          eventId: "evt_fatura_001",
          eventType: "invoice.created",
          payload: { invoiceNo: "FAT-001" },
        }),
        headers: {
          Authorization: "Bearer noa_live_webhook",
          "Content-Type": "application/json",
        },
        method: "POST",
      }),
    );

    expect(response.status).toBe(200);
    const responseBody = await response.json();
    expect(responseBody).toEqual(
      expect.objectContaining({
        ok: true,
        eventEnvelope: expect.objectContaining({
          data: { invoiceNo: "FAT-001" },
          eventId: "evt_fatura_001",
          eventType: "invoice.created",
          occurredAt: expect.any(String),
          version: "2026-07",
        }),
        data: expect.objectContaining({
          eventType: "invoice.created",
          plan: expect.objectContaining({ matchingEndpointCount: 1 }),
          attempts: [
            expect.objectContaining({
              endpointId: "webhook-endpoint-1",
              headers: expect.objectContaining({
                "x-noa-webhook-signature": "[signature will be generated by worker]",
              }),
            }),
          ],
        }),
      }),
    );
    expect(JSON.parse(responseBody.data.body)).toEqual({
      data: { invoiceNo: "FAT-001" },
      eventId: "evt_fatura_001",
      eventType: "invoice.created",
      occurredAt: expect.any(String),
      version: "2026-07",
    });
    expect(authenticateBearerApiKeyMock).toHaveBeenCalledWith({
      authorizationHeader: "Bearer noa_live_webhook",
      repository: apiKeyRepositoryMock,
      requiredScopes: ["webhooks"],
    });
    expect(webhookEndpointRepositoryMock.list).toHaveBeenCalledWith({
      scope: expect.objectContaining({
        companyId: "company-1",
        periodId: "period-1",
        tenantId: "tenant-1",
      }),
    });
  });

  test("rejects malformed requests after authenticating the webhook key", async () => {
    authenticateBearerApiKeyMock.mockResolvedValue({
      ok: true,
      data: { apiKey: { id: "api-key-webhooks" } },
    });

    const response = await POST(
      new Request("http://localhost/api/webhooks/dry-run", {
        body: JSON.stringify({ eventType: "unknown" }),
        headers: { Authorization: "Bearer noa_live_webhook" },
        method: "POST",
      }),
    );

    expect(response.status).toBe(400);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      errors: ["Desteklenen bir webhook olay türü seçilmelidir."],
    });
    expect(webhookEndpointRepositoryMock.list).not.toHaveBeenCalled();
  });

  test("rejects an empty or oversized caller event id before endpoint lookup", async () => {
    authenticateBearerApiKeyMock.mockResolvedValue({
      ok: true,
      data: { apiKey: { id: "api-key-webhooks" } },
    });

    const response = await POST(
      new Request("http://localhost/api/webhooks/dry-run", {
        body: JSON.stringify({ eventId: " ", eventType: "invoice.created" }),
        headers: { Authorization: "Bearer noa_live_webhook" },
        method: "POST",
      }),
    );

    expect(response.status).toBe(400);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      errors: ["Webhook olay kimliği 1 ile 120 karakter arasında olmalıdır."],
    });
    expect(webhookEndpointRepositoryMock.list).not.toHaveBeenCalled();
  });

  test("returns a bearer challenge without a valid webhook key", async () => {
    authenticateBearerApiKeyMock.mockResolvedValue({
      ok: false,
      errors: ["Bearer API anahtarı zorunludur."],
      status: 401,
    });

    const response = await POST(
      new Request("http://localhost/api/webhooks/dry-run", { method: "POST" }),
    );

    expect(response.status).toBe(401);
    expect(response.headers.get("www-authenticate")).toBe("Bearer");
  });
});
